new_lending/authentication/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.Authenticate.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('regist/', views.Registration.as_view(), name='regist'),
    path('reset-password/', views.ResetPassword.as_view(), name='reset_password'),
    path('password-reset-confirm/<uidb64>/<token>', views.ResetPasswordConfirm.as_view(), name='password_reset_confirm'),
]

new_lending/cart/urls.py
from django.urls import path, include, re_path

from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<uuid:product_id>/', views.AddCart.as_view(), name = 'cart_add'),
    path('details/', views.Details.as_view(), name='details'),
    path('order/done/', views.TakeOrder.as_view(), name = 'order_done'),
    path('order/information/', views.TypeOrderInformation.as_view(), name = 'order_information'),
    path('order/<uuid:order_id>', views.OrderView.as_view(), name = 'order')
]

new_lending/lending/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib import admin

app_name = 'lending'

urlpatterns = [
    path('',views.empty, name = "empty"),
    path('home/',views.Home.as_view(), name= "home"),
    path('catalog/', views.CatalogView.as_view(), name = "catalog"),
    path('sale/',views.SaleView.as_view(), name = 'sale'),
    path('partners/',views.About_usList.as_view(), name ='about_us'),
    path('partners/<slug:slugy>/', views.ProductList.as_view(),name = 'products_list'),
    path('product/<uuid:pk>/',views.ProductView.as_view(), name = 'product_page'),
]

new_lending/new_lending/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

from new_lending import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('',include('lending.urls', namespace='lending')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('authentication/',include('authentication.urls',namespace= 'authentication')),
    path('',include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler_404 = page_not_found
admin.site.site_header = "Administration panel"
admin.site.index_title = "Data"

new_lending/templates/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/pag.css'%}">
    <link rel="stylesheet" href="{%static 'css/base_styles.css'%}">
    <link rel="icon" href="{%static 'images/favicon/favicon.ico'%}" >
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    {%block styles%}
    {%endblock%}
</head>
<title>{{title}}</title>
<body>
<div class="all_place">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'lending:home' %}">Seller</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'lending:home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lending:sale' %}">Sale</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'lending:catalog' %}">Catalog</a>
          </li>

        </ul>
        </li>
        </ul>
      </div>
      <a href="{% url 'cart:details' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
      </svg>
        </a>
      <ul class="navbar-nav">
        <li class="nav-item">
          {%if user.is_authenticated%}
          <li><a class="nav-link active" aria-current="page" href="{%url 'authentication:logout'%}">Logout</a><li>
          <li><a class="nav-link active" aria-current="page" href="{%url 'authentication:profile'%}">Profile</a><li>
          {%else%}
          <li><a class="nav-link active" aria-current="page" href="{%url 'authentication:login'%}">Login</a></li>
          <li><a class="nav-link active" aria-current="page" href="{%url 'authentication:regist'%}">Registration</a></li>
          {%endif%}
        </li>
      </ul>
    </div>
  </nav>
{%block content%}
<title>Home</title>
{%endblock%}

{%block pagination%}
{%endblock%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 <footer class="footer">
     <div class="container">
      <div class="row">
        <div class="footer-col">
          <h4>company</h4>
          <ul class="ul-type">
            <li><a href="{%url 'lending:about_us'%}">about us</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>online shop</h4>
          <ul class="ul-type">
            <li><a href="{%url 'lending:catalog'%}">catalog</a></li>
            <li><a href="{%url 'authentication:profile'%}">profile</a></li>

          </ul>
        </div>
        <div class="footer-col">
          <h4>follow us</h4>
          <div class="social-links">
            <a href="https://t.me/taliavi1"><img src="{%static 'images/telegram_svg/telegram.svg'%}"></a>
          </div>
        </div>
      </div>
     </div>
  </footer>
</div>
</body>
</html>
{%load static%}
<html lang="en">