new_lending/authentication/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.Authenticate.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('regist/', views.Registration.as_view(), name='regist'),
    path('reset-password/', views.ResetPassword.as_view(), name='reset_password'),
    path('password-reset-confirm/<uidb64>/<token>', views.ResetPasswordConfirm.as_view(), name='password_reset_confirm'),
]

new_lending/cart/urls.py
from django.urls import path, include, re_path

from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<uuid:product_id>/', views.AddCart.as_view(), name = 'cart_add'),
    path('details/', views.Details.as_view(), name='details'),
    path('order/done/', views.TakeOrder.as_view(), name = 'order_done'),
    path('order/information/', views.TypeOrderInformation.as_view(), name = 'order_information'),
    path('order/<uuid:order_id>', views.OrderView.as_view(), name = 'order')
]

new_lending/new_lending/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

from new_lending import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('',include('lending.urls', namespace='lending')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('authentication/',include('authentication.urls',namespace= 'authentication')),
    path('',include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler_404 = page_not_found
admin.site.site_header = "Administration panel"
admin.site.index_title = "Data"

new_lending/authentication/models.py
from django.db import models

# Create your models here.

new_lending/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class Authentication(AuthenticationForm):
    username = forms.CharField(max_length=255,widget=forms.TextInput(attrs = {
        'id' : "username",
    }))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs = {
        'id' : "password",
    }))
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

class Regist(UserCreationForm):
    email = forms.EmailField(label= 'Email',max_length=255, widget=forms.TextInput(attrs={
        'id': "username",
    }))
    username = forms.CharField(label='Username',max_length=255,widget=forms.TextInput(attrs={
        'id': "username",
    }))
    password1 = forms.CharField(label= 'Password', max_length=32, widget=forms.PasswordInput(attrs={
        'id': "password",
    }))
    password2 = forms.CharField(label= 'Confirm password',max_length=32, widget=forms.PasswordInput(attrs={
        'id': "password",
    }))
    class Meta:
        model = get_user_model()
        fields = ['email','username', 'password1','password2']


    def clean_password2(self):
        print(self.cleaned_data['password1'], self.cleaned_data['password2'])
        if self.cleaned_data['password1'] == self.cleaned_data['password2']:
            #print(self.cleaned_data['password1'],self.cleaned_data['password2'])
            return self.cleaned_data['password2']
        raise forms.ValidationError('Passwords not equals')

    def clean_email(self):
        if not get_user_model().objects.filter(email = self.cleaned_data['email']).exists:
            raise forms.ValidationError('This Email already registrate')
        return self.cleaned_data['email']

    def clean_username(self):
        print(self.cleaned_data['username'])
        if not get_user_model().objects.filter(username = self.cleaned_data['username']).exists:
            print(get_user_model().objects.filter(username = self.cleaned_data['username']))
            raise forms.ValidationError('This username already exist. Please create new')
        return self.cleaned_data['username']

    def save(self, commit=True):
        user = get_user_model().objects.create(
            username = self.cleaned_data['username'],
            email = self.cleaned_data['email'],
        )
        user.set_password(self.cleaned_data['password2'])
        user.save()
        return user


class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label= 'Enter your email address, which you had been used for registration',max_length=64)


    def clean_email(self):
        if not get_user_model().objects.filter(email = self.cleaned_data['email']).exists:
            raise forms.ValidationError('This email not registrate yet')
        return self.cleaned_data['email']

class ResetPasswordConfirmForm(forms.Form):
    password1 = forms.CharField(label= 'Type new password',max_length=64, widget=forms.PasswordInput)
    password2 = forms.CharField(label= 'Confirm password',max_length=64, widget=forms.PasswordInput)


    def clean_password2(self):
        if not self.cleaned_data['password1'] == self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords not equals')
        return self.cleaned_data['password2']

new_lending/authentication/views.py
from typing import Any
import datetime
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.middleware import get_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, DetailView, TemplateView, ListView
from django.core.mail import send_mail
from .forms import Authentication, Regist, ResetPasswordForm, ResetPasswordConfirmForm
from new_lending import settings
from django import utils

from lending.models import usersOrders


class Authenticate(LoginView):
    form_model = Authentication
    template_name = 'authentication.html'


class Profile(LoginRequiredMixin,ListView):
    template_name = 'profile.html'
    model = get_user_model()
    context_object_name = 'orders'

    def get_queryset(self):
        return usersOrders.objects.filter(userLogin_id = get_user(self.request).id)


class Registration(FormView):
    template_name = 'registration.html'
    form_class = Regist

    # def get_success_url(self):
    #     return reverse_lazy('authentication:login')

    def form_valid(self, form):
        form.save(commit = False)
        return redirect('authentication:login')



class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('authentication:login')


class ResetPassword(FormView):
    form_class = ResetPasswordForm
    template_name = 'pass_reset.html'

    def form_valid(self, form):
        url = get_user_model().get_password_reset_url(get_user_model().objects.get(email = form.cleaned_data['email']))
        send_mail("Reset password", f"Join to url to reset your password\n{url}", settings.EMAIL_HOST_USER, [form.cleaned_data['email']])
        time_success = datetime.datetime.now() + datetime.timedelta(minutes=5)
        return render(self.request, 'reset_send.html')


class ResetPasswordConfirm(FormView):
    template_name = 'password_reset_confirm.html'
    form_class = ResetPasswordConfirmForm

    def form_valid(self, form):
        user_id = utils.http.urlsafe_base64_decode(self.kwargs['uidb64'])#self.kwargs['uidb64'].
        user = get_user_model().objects.get(id = user_id)
        user.set_password(form.cleaned_data['password2'])
        user.save()
        return redirect('authentication:login')

new_lending/authentication/templates/authentication.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/authentication.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {%csrf_token%}
        <h3>Login Here</h3>
        {{form}}
        <button type="submit">Log In</button>
        <a href="{%url 'authentication:reset_password'%}">Forget password</a>

    </form>


{%endblock%}

new_lending/authentication/templates/pass_reset.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/authentication.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {%csrf_token%}
        <h3>Reset Password</h3>
        {{form}}
        <button type="submit">Send</button>
    </form>


{%endblock%}

new_lending/authentication/templates/password_reset_confirm.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/authentication.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {%csrf_token%}
        <h3>Change Password</h3>
        {{form}}
        <button type="submit">Send</button>
    </form>


{%endblock%}

new_lending/authentication/templates/profile.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<h1>Your orders</h1>
{%for order in orders%}
<div class="order">
    <span>id: {{order.id}},</span>
    <span>name: {{order.order_name}},</span>
    <span>phone: {{order.order_phone}},</span>
    <span>second_name: {{order.order_second_name}},</span>
    <span>place: {{order.order_place}},</span>
</div>
{%endfor%}
{%endblock%}

new_lending/authentication/templates/registration.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/authentication.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post" class="height">
        {%csrf_token%}
        <h3>Sign up</h3>
        {{form}}
        <button type="submit">Sign up</button>
    </form>


{%endblock%}

new_lending/authentication/templates/reset_send.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{% static 'css/authentication.css' %}" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {%csrf_token%}
        <h3>We're sent email with instructions to your email :)</h3>

    </form>


{%endblock%}