new_lending/cart/urls.py
from django.urls import path, include, re_path

from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<uuid:product_id>/', views.AddCart.as_view(), name = 'cart_add'),
    path('details/', views.Details.as_view(), name='details'),
    path('order/done/', views.TakeOrder.as_view(), name = 'order_done'),
    path('order/information/', views.TypeOrderInformation.as_view(), name = 'order_information'),
    path('order/<uuid:order_id>', views.OrderView.as_view(), name = 'order')
]

new_lending/lending/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib import admin

app_name = 'lending'

urlpatterns = [
    path('',views.empty, name = "empty"),
    path('home/',views.Home.as_view(), name= "home"),
    path('catalog/', views.CatalogView.as_view(), name = "catalog"),
    path('sale/',views.SaleView.as_view(), name = 'sale'),
    path('partners/',views.About_usList.as_view(), name ='about_us'),
    path('partners/<slug:slugy>/', views.ProductList.as_view(),name = 'products_list'),
    path('product/<uuid:pk>/',views.ProductView.as_view(), name = 'product_page'),
]

new_lending/new_lending/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

from new_lending import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('',include('lending.urls', namespace='lending')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('authentication/',include('authentication.urls',namespace= 'authentication')),
    path('',include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler_404 = page_not_found
admin.site.site_header = "Administration panel"
admin.site.index_title = "Data"

new_lending/lending/models.py
from functools import partial
from django import utils
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
import uuid
import json

from new_lending import settings


class inStockProduct(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(stock = 1)

class Companys(models.Model):
    nameOfCopmany = models.CharField(primary_key= True,max_length= 30,verbose_name='Name')
    Descripton = models.TextField(max_length=255, verbose_name= 'Description')
    image = models.ImageField()
    slug = models.SlugField(blank= False, unique= True)
     
    
    def __str__(self) -> str:
        return self.nameOfCopmany

    def get_absolute_url(self):
        return reverse('lending:products_list', kwargs= {'slugy' : self.slug})
    
    class Meta:
        verbose_name = "Companys"
        verbose_name_plural = "Companys"

class Product(models.Model):

    class Status(models.IntegerChoices):

        inStock = 1, 'In stock'
        outStock = 0, 'Out stock'


    productModel = models.CharField(max_length= 255,verbose_name="Product")
    descripton = models.TextField(max_length=255, default='any description')
    id = models.UUIDField(unique= True,blank= False, default= uuid.uuid4,primary_key=True)
    Maker = models.ForeignKey('Companys', on_delete= models.PROTECT,null=True,related_name='maker')
    stock = models.IntegerField(choices= Status.choices)
    cost = models.IntegerField(null= False)
    tags = models.ManyToManyField('Tags', blank = True, related_name= 'tag')
    photo = models.ImageField(upload_to= 'photos/%Y/%m/%d', blank= True, null= True, verbose_name='photo')


    objects = models.Manager()
    product = inStockProduct()

    def __str__(self) -> str:
        return self.productModel

    def get_absolute_url(self):
        return reverse('lending:product_page', kwargs={'pk' : self.id})

    class Meta:
        ordering = ['-cost']
        indexes = [
            models.Index(fields=['-cost'])
        ]




class usersOrders(models.Model):

    class orderStatus(models.IntegerChoices):
        orderAdopted = 0, 'Adopted'
        orderAssebmbled = 1, 'Assembled'
        orderSended = 2, 'Sended'
        orderDelivered = 3, 'Delivered'

    orderPositions = models.ManyToManyField('Product', blank=False, related_name='products', null= True)
    userLogin = models.ForeignKey('User', on_delete= models.PROTECT)
    order_name = models.CharField(max_length=64, blank= False, verbose_name='Name')
    order_surname = models.CharField(max_length=64, blank= False)
    order_second_name = models.CharField(max_length=64, blank= False)
    order_phone = models.CharField(max_length=64, blank= False)
    order_place = models.CharField(max_length=64, blank=False)
    status = models.IntegerField(blank= False, choices= orderStatus.choices)
    receipt = models.ImageField(blank= False)
    cart_url = models.CharField(blank= False)
    id = models.UUIDField(primary_key=True, blank=False,default=uuid.uuid4, unique=True)
    quantities = models.CharField(null= False, blank= False)
    



class Tags(models.Model):
    name = models.CharField(max_length= 100)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_slug(self):
        return slugify(self.name, allow_unicode= True)

    def get_absolute_url(self):
        return reverse('lending:catalog', kwargs= {'tag' : self.slug})


class Sizes(models.Model):
    id = models.IntegerField(primary_key= True)
    name = models.CharField(max_length=2)
    products = models.ManyToManyField('Product', related_name='sizes')




class User(AbstractUser):


    def get_password_reset_url(self):
        base64_encoded_id = utils.http.urlsafe_base64_encode(utils.encoding.force_bytes(self.id))
        token = PasswordResetTokenGenerator().make_token(self)
        reset_url_args = {'uidb64': base64_encoded_id, 'token': token}
        reset_path = reverse('authentication:password_reset_confirm', kwargs=reset_url_args)
        reset_url = f'{settings.BASE_URL}{reset_path}'
        return reset_url

new_lending/lending/forms.py
from django import forms


class Filters(forms.Form):
    price_range = forms.IntegerField(max_value=150000)
    size = forms.CharField(max_length=2)
    kind = forms.CharField(max_length=32)
    sex = forms.CharField(max_length=6)
    creator = forms.CharField(max_length=32)


    def clean_price_range(self):
        if self.cleaned_data['price_range']:
            try:
                return int(self.cleaned_data['price_range'])
            except:
                raise forms.ValidationError('Weird. Why you try broke my filter :(')

        else:
            return None

    def clean_size(self):
        if self.cleaned_data['size']:
            try:
                return int(self.cleaned_data['size'])
            except:
                raise forms.ValidationError('Oh. Stop broke my filters')

        else:
            return None

    def clean_kind(self):
        if self.cleaned_data['kind']:
            try:
                return str(self.cleaned_data['kind'])
            except:
                raise forms.ValidationError('You again...')
        else:
            return None

    def clean_sex(self):
        if self.cleaned_data['sex']:
            if self.cleaned_data['sex'] not in ['women', 'man']:
                raise forms.ValidationError('Are you kidding?')
        else:
            return None

    def clean_creator(self):
        if self.cleaned_data['creator']:
            try:
                return str(self.cleaned_data['creator'])
            except:
                raise forms.ValidationError('HEHHE. No.')

        else:
            return None

new_lending/lending/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.template.loader import render_to_string
from .models import Companys, Tags, Product, Sizes
from django.views.generic import ListView, TemplateView,DetailView, FormView
#from .forms import Authentication
from django.urls import reverse, reverse_lazy
from cart import forms
from cart.forms import CartAddProductForm
from cart.cart import Cart

from .utils import DataMixin

tag_data = Tags.objects.all()


def empty(request):
    return redirect('lending:home')


class Home(TemplateView):
    template_name = 'home_page.html'
    extra_context = {'title' : 'Home'}




class About_usList(ListView):
    paginate_by = 3
    model = Companys
    template_name = 'about_us.html'
    context_object_name = 'companys'
    extra_context = {'title': 'About Us'}





class ProductList(DataMixin,ListView):
    paginate_by = 3
    template_name = 'products_list.html'
    context_object_name = 'products'
    title_page = 'Products'
    #extra_context = {'title': 'Products','cart_product_form': CartAddProductForm()}


    def get_queryset(self) -> QuerySet[Any]:
        return Product.product.filter(Maker = Companys.objects.get(slug = self.kwargs['slugy']))


class CatalogView(DataMixin,ListView):
    title_page = 'Catalog'
    paginate_by = 3
    template_name = 'catalog.html'
    model = Product
    context_object_name = 'products'
    #extra_context = {'form' : CartAddProductForm()}

    def get_queryset(self):
        products = Product.objects.filter(stock = 1)
        if 'size' in self.request.GET:
            size = Sizes.objects.get(name = self.request.GET['size'])
            products = size.products.all()

        if 'kind' in self.request.GET:
            kind = Tags.objects.get(name = self.request.GET['kind'])
            products = products.filter(tags__slug = self.request.GET['kind'])

        if 'creator' in self.request.GET:
            products = products.filter(Maker_id__slug = self.request.GET['creator'])

        if 'sex' in self.request.GET:
            products = products.filter(tags__slug = self.request.GET['sex'])

        return products


class SaleView(DataMixin,ListView):
    title_page = 'Sale'
    paginate_by = 3
    template_name = 'sale.html'
    context_object_name = 'products'


    def get_queryset(self):
        return Product.objects.filter(tags__pk = 8)





class ProductView(DataMixin,FormView):
    template_name = 'productPage.html'
    form_class = CartAddProductForm


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(pk = self.kwargs['pk'])
        context['title'] = Product.objects.get(pk = self.kwargs['pk']).productModel
        return context
    
   

    

new_lending/lending/templates/about_us.html
{%extends 'base.html'%}
{%load static%}

<body>

{%block content%}
<div class="my_text">
    <h1> Why our?</h1>
    <h2>Because these companies choose our </h2>
</div>
<div class="card-group">
    {%for company in companys%}
    <div class="card">
        <img src="{{company.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{company.nameOfCopmany}}</h5>
            <p class="card-text">{{company.Descripton}}</p>
            <a href="{{company.get_absolute_url}} " class="btn btn-primary">To see products</a>
      </div>
    </div>
    {%endfor%}
</div>
{%endblock%}
{%block pagination%}
    <ul class="pagination">
    {%for page in paginator.page_range%}
    {%if paginator.page_number == page%}
        <li><a class="active" href="?page={{page}}">{{page}}</a></li>
    {%else%}
        <li><a href="?page={{page}}">{{page}}</a></li>
    {%endif%}
    {%endfor%}
  </ul>
    {%endblock%}
</body>
</html>

new_lending/lending/templates/catalog.html
{%extends "base.html" %}
{%load static%}


{%block styles%}

<link rel="stylesheet" href="{%static 'css/product_card.css'%}">
<link rel="stylesheet" href="{%static 'css/catalog_filters.css'%}">
{%endblock%}
{%block content%}
<div class="text_upper_filters">
    <h2>Filters</h2>
</div>

<div class="filters">
    <form method="get">
<!--    I'll use only used parameters-->
        <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Size
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><span class = "dropdown-item">25 <input type="checkbox" name="size" value="25"></span></li>
          <li><span class = "dropdown-item">29 <input type="checkbox" name="size" value="29"></span></li>
          <li><span class = "dropdown-item">34 <input type="checkbox" name="size" value="34"></span></li>
          <li><span class = "dropdown-item">39 <input type="checkbox" name="size" value="39"></span></li>
          <li><span class = "dropdown-item">44 <input type="checkbox" name="size" value="44"></span></li>
      </ul>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Kind
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><span class = "dropdown-item">Pants <input type="checkbox" name="kind" value="pants"></span></li>
        <li><span class = "dropdown-item">Trainers <input type="checkbox" name="kind" value="trainers"></span></li>
        <li><span class = "dropdown-item">Jacket <input type="checkbox" name="kind" value="jacket"></span></li>
      </ul>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Creator
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><span class = "dropdown-item">Adidas <input type="checkbox" name="creator" value="adidas"></span></li>
        <li><span class = "dropdown-item">ROLEX <input type="checkbox" name="creator" value="rolex"></span></li>
        <li><span class = "dropdown-item">Nike <input type="checkbox" name="creator" value="nike"></span></li>
        <li><span class = "dropdown-item">The North Face <input type="checkbox" name="creator" value="the_north_face"></span></li>
        <li><span class = "dropdown-item">Lacoste <input type="checkbox" name="creator" value="lacoste"></span></li>
      </ul>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Sex
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><span class = "dropdown-item">Man <input type="checkbox" name="sex" value="man"></span></li>
        <li><span class = "dropdown-item">Women <input type="checkbox" name="sex" value="women"></span></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
      </ul>
    <div class="btn">
        <button type="submit"> Filter</button>
    </div>
    </form>
    </div>
<div class="text_under_filters">
    <h2>
        Goods
    </h2>
</div>
<div class="card-group">
    {%for product in products%}
    <div class="card">
        <form action="{%url 'cart:cart_add' product.id%}" method="post">
        {%csrf_token%}
        <img src="{{product.photo.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{product.productModel}}</h5>
            <p class="card-text">{{product.Descripton}}</p>
            <h6 class="card-title">{{product.cost}}</h6>
            {{ cart_product_form.as_p}}
          <button class="btn btn-primary" type="submit">Add to cart</button>
        </form>
        <a href="{% url 'lending:product_page' product.id%}" type="button">View more</a>
      </div>
    </div>
    {%endfor%}
</div>




{%endblock%}

{%block pagination%}
    <ul class="pagination">
    {%for page in paginator.page_range%}
    {%if paginator.page_number == page%}
        <li><a class="active" href="?page={{page}}">{{page}}</a></li>
    {%else%}
        <li><a href="?page={{page}}">{{page}}</a></li>
    {%endif%}
    {%endfor%}
  </ul>
    {%endblock%}

new_lending/lending/templates/home_page.html
{%extends 'base.html'%}

{%block content%}
<h1>This is my first backend practice. Now all fronted is not so good</h1>
<h2>Maybe in the future when I'll practice js or something I'll do frontend, I hope ^)</h2>
<h2>In backend you can see catalog, cart, authentication(without jwt, 'cause I not used rest_fraemwork), cart(but cart I save only in session, 'cause I think this way is more difficult)</h2>
<h2>But also I did a function, which create and save order, but I haven't opportunities to add pay system</h2>
<h2>Also I haven't opportunities to check order status, 'cause I don't have any equipment for this.</h2>
<h2>Finally, I connect SMTP to my project and I realized function, which generate PDF with order information and send this to user.</h2>
{%endblock%}

new_lending/lending/templates/productPage.html
{%extends 'base.html'%}
{% load static %}
{%block content%}
{%block styles%}

<link rel="stylesheet" href="{%static 'css/product_page.css'%}">

{%endblock%}
<form method="post" action="{%url 'cart:cart_add' product.id%}">
    {%csrf_token%}
    <div class="card">
    <img src="{{product.photo.url}}" alt="Trainers" class="product_image">


    <h1>{{product.productModel}}</h1>
    <p class="price">{{product.cost}}</p>
    <p>{{product.descripton}}</p>
    {{ cart_product_form.as_p}}
    <p><button>Add to Cart</button></p>
</div>
</form>
{%endblock%}

new_lending/lending/templates/products_list.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}

<link rel="stylesheet" href="{%static 'css/product_card.css'%}">

{%endblock%}
{%block content%}
<div class="card-group">
{%for product in products%}
    <div class="card">
        <form action="{%url 'cart:cart_add' product.id%}" method="post">
        {%csrf_token%}
        <img src="{{product.photo.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{product.productModel}}</h5>
            <p class="card-text">{{product.Descripton}}</p>
            <h6 class="card-title">{{product.cost}}</h6>
            {{ cart_product_form.as_p}}
          <button class="btn btn-primary" type="submit">Add to cart</button>
        </form>
        <a href="{% url 'lending:product_page' product.id%}" type="button">View more</a>
      </div>
    </div>
{%endfor%}
</div>


{%endblock%}

new_lending/lending/templates/sale.html
{%extends "base.html"%}
{%load static%}


{%block styles%}

<link rel="stylesheet" href="{%static 'css/product_card.css'%}">
<link rel="stylesheet" href="{%static 'css/catalog_filters.css'%}">
{%endblock%}
{%block content%}


<div class="card-group">
    {%for product in products%}
    <div class="card">
        <form action="{%url 'cart:cart_add' product.id%}" method="post">
        {%csrf_token%}
        <img src="{{product.photo.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{product.productModel}}</h5>
            <p class="card-text">{{product.Descripton}}</p>
            <h6 class="card-title">{{product.cost}}</h6>
            {{ cart_product_form.as_p}}
          <button class="btn btn-primary" type="submit">Add to cart</button>
        </form>
        <a href="{% url 'lending:product_page' product.id%}" type="button">View more</a>
      </div>
    </div>
{%endfor%}
</div>
{%endblock%}
</body>