new_lending/cart/urls.py
from django.urls import path, include, re_path

from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<uuid:product_id>/', views.AddCart.as_view(), name = 'cart_add'),
    path('details/', views.Details.as_view(), name='details'),
    path('order/done/', views.TakeOrder.as_view(), name = 'order_done'),
    path('order/information/', views.TypeOrderInformation.as_view(), name = 'order_information'),
    path('order/<uuid:order_id>', views.OrderView.as_view(), name = 'order')
]

new_lending/new_lending/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

from new_lending import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('',include('lending.urls', namespace='lending')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('authentication/',include('authentication.urls',namespace= 'authentication')),
    path('',include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler_404 = page_not_found
admin.site.site_header = "Administration panel"
admin.site.index_title = "Data"

new_lending/cart/models.py
from django.db import models

# Create your models here.

new_lending/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderInformation(forms.Form):
    name = forms.CharField(max_length=64, widget=forms.TextInput())
    surname = forms.CharField(max_length=64, widget=forms.TextInput())
    second_name = forms.CharField(max_length=64, widget=forms.TextInput())
    phone_number = forms.CharField(max_length=64, widget=forms.TextInput())
    order_place = forms.CharField(max_length=255,widget=forms.TextInput())

new_lending/cart/views.py
import ast
import json
import uuid

from django.contrib.auth import get_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_POST
from django.views.generic import FormView, ListView, DetailView, TemplateView
from lending.models import Product

from .CreateOrder import CreateOrder
from .cart import Cart
from .forms import CartAddProductForm, OrderInformation
from new_lending import settings

from lending.models import usersOrders


class AddCart(LoginRequiredMixin,FormView):
    form_class = CartAddProductForm

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        cart.add(product_id= str(self.kwargs['product_id']),
                 quantity=request.POST['quantity'],
                 update_quantity=request.POST['update'])
        return redirect('cart:details')

class Details(LoginRequiredMixin,ListView):
    model = Product
    template_name = 'cart.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        cart = Cart(self.request)
        context['cart'] = cart.cart
        context['total_cost'] = str(cart.get_total_price())
        return context

class TakeOrder(LoginRequiredMixin,FormView):
    template_name = 'takeorder.html'


    def post(self, request, *args, **kwargs):
        order = CreateOrder
        order_id = str(uuid.uuid4())
        order_url = order.create_pdf(number= order_id)
        email = EmailMessage(
            "Order Information",
            "In this file you can this all information about order",
            f"{settings.EMAIL_HOST_USER}",
            [f"{get_user(request).email}"],
        )
        email.attach_file(order_url)
        email.send()
        order.create_order(pdf = order_url, request=request, id = order_id)
        request.session['cart'] = {}

        return redirect('lending:home')


class OrderView(LoginRequiredMixin, TemplateView):
    template_name = 'order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        order = usersOrders.objects.get(pk = self.kwargs['order_id'])
        context['order_positions'] = order.orderPositions.all()
        context['order_quantities'] = ast.literal_eval(order.quantities)
        context['total_price'] = 0

        for product in context['order_positions']:
            context['total_price'] += product.cost * int(context['order_quantities'].get(str(product.id)))

        return context


class TypeOrderInformation(LoginRequiredMixin, FormView):

    form_class = OrderInformation
    template_name = 'order_information.html'

new_lending/cart/templates/cart.html
{%extends 'base.html'%}
{%load static%}

  <header id="site-header">
    <div class="container">
      <h1>Shopping cart <span>[</span> <em><a href="https://codepen.io/tag/rodeo-007" target="_blank">CodePen Challange</a></em> <span class="last-span is-open">]</span></h1>
    </div>
  </header>
{%block styles%}
<link rel="stylesheet" href="{%static 'css/cart.css'%}">
{%endblock%}
{%block content%}
<form action="{% url 'cart:order_information' %}" method="post">
  <div class="container mt-5 mb-5">
            <div class="d-flex justify-content-center row">
                <div class="col-md-8">
                    <div class="p-2">
                        <h4>Shopping cart</h4>

                    </div>

                    {%csrf_token%}
                  {%for _, product in cart.items%}
                    <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
                        <div class="mr-1"><img class="rounded" src="{{product.image}}" width="70"></div>
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product.size}}</span></div>
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product.name}}</span>

                        </div>
                        <div class="d-flex flex-row align-items-center qty">Quantity : {{product.quantity}}</i>
                            <h5 class="text-grey mt-1 mr-1 ml-1"></h5></div>
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product.cost}}</span>
                            <div class="d-flex flex-row product-desc">
                                <div class="color"><span class="font-weight-bold">Price for one</span></div>
                            </div>
                        </div>
                        <div>
                            <h5 class="text-grey">{{product.total_cost}}</h5>
                        </div>

                    </div>
                  {%endfor%}
                    </div>
                <input type="hidden" value="a">
                <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">Total Price: {{total_cost}}</div>
<!--                    <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded"><input type="text" class="form-control border-0 gift-card" placeholder="discount code/gift card"><button class="btn btn-outline-warning btn-sm ml-2" type="button">Apply</button></div>-->
                    <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded">
                        <button class="btn btn-warning btn-block btn-lg ml-2 pay-button" type="submit">Proceed to Pay</button>
                    </div>
                </div>
            </div>
        </div>
</form>
{%endblock%}

new_lending/cart/templates/order.html
{%extends 'base.html'%}
{%load static%}
{%load filters%}
  <header id="site-header">
    <div class="container">
      <h1>Shopping cart <span>[</span> <em><a href="https://codepen.io/tag/rodeo-007" target="_blank">CodePen Challange</a></em> <span class="last-span is-open">]</span></h1>
    </div>
  </header>
{%block styles%}
<link rel="stylesheet" href="{%static 'css/cart.css'%}">
{%endblock%}
{%block content%}
  <div class="container mt-5 mb-5">
            <div class="d-flex justify-content-center row">
                <div class="col-md-8">
                    <div class="p-2">
                        <h4>Your order</h4>

                    </div>
                  {%with 0 as sum%}
                  {%for product in order_positions%}
                    <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
                        <div class="mr-1"><img class="rounded" src="{{product.photo.url}}" width="70"></div>
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product.size}}</span></div>
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product}}</span>
                        </div>
                        {%with product.id as product_id%}
                        <div class="d-flex flex-row align-items-center qty">Quantity : {{order_quantities|get_value_from_dict:product.id}}
                            <h5 class="text-grey mt-1 mr-1 ml-1"></h5></div>
                        {%endwith%}
                        <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">{{product.cost}}</span>
                            <div class="d-flex flex-row product-desc">
                                <div class="color"><span class="font-weight-bold">Price for one</span></div>
                            </div>
                        </div>

                        <div class="d-flex align-items-center"></div>
                    </div>
                  {%endfor%}
                  {%endwith%}
                    </div>
                <input type="hidden" value="a">
                <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">Total Price: {{total_price}}</div>
                </div>
            </div>
        </div>

{%endblock%}

new_lending/cart/templates/order_information.html
{%extends 'base.html'%}
{%load static%}
{%block styles%}
<link rel="stylesheet" href="{%static 'css/order_information_styles.css'%}">
{%endblock%}
{%block content%}

<form action="{%url 'cart:order_done' %}" method="post">
    {%csrf_token %}
    {{form}}
    <button type="submit" class="order"></button>
</form>
{%endblock%}

new_lending/cart/templates/takeorder.html
{%extends 'base.html'%}
{%load static%}

{%block content%}
<h1>Thanks for take order</h1>
{%endblock%}